substitutions:
  # Set the device name
  name: devicename
  # Set the friendly name
  friendly_name: friendly
  # Provide the wifi SSID
  wifi: !secret wifi_ssid
  #Provide the wifi password
  wifi_pass: !secret wifi_password
  #Provide an OTA password:
  ota_pass: "trustbutverifywalkingwithabigstick"

packages:
  micro_radar:
    url: https://github.com/FriedCheese2006/HomeAssistant
    file: ESPHome/ESP32_Micro_Radar/ESP32_S2/ESP32_Mini_Radar.yaml
    refresh: 1h

### No modifications needed below here ###
####################################################################################

esphome:
  name: $name
  friendly_name: $friendly_name
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_cpu: 80000000L
  name_add_mac_suffix: false